// src/lib/components/product-card.svelte
<script lang="ts">
	import { ShoppingCart } from 'lucide-svelte';
	import { cartItems } from '$lib/store.svelte';
	import type { Product } from '$lib/stores/products.svelte.js';

	let { product } = $props<{ product: Product }>();

	function addToCart() {
		cartItems.addItem(product);
	}
</script>

<div class="bg-card text-card-foreground rounded-lg border border-border overflow-hidden hover:shadow-lg transition-shadow">
	<div class="h-48 bg-secondary overflow-hidden">
		<img 
			src={product.image || "/placeholder.svg"} 
			alt={product.name}
			class="w-full h-full object-cover hover:scale-105 transition-transform duration-300"
		/>
	</div>
	<div class="p-4">
		{#if product.rating}
			<div class="flex items-center gap-1 mb-2">
				<span class="text-xs font-semibold text-accent">★</span>
				<span class="text-xs text-muted-foreground">{product.rating}</span>
			</div>
		{/if}
		<h3 class="text-lg font-semibold mb-2 text-card-foreground">{product.name}</h3>
		<p class="text-sm text-muted-foreground mb-3 line-clamp-2">{product.description}</p>
		<div class="flex items-center justify-between">
			<div class="flex flex-col">
				<span class="text-2xl font-bold text-accent">${product.price.toFixed(2)}</span>
				{#if product.originalPrice}
					<span class="text-xs text-muted-foreground line-through">${product.originalPrice.toFixed(2)}</span>
				{/if}
			</div>
			<button 
				onclick={addToCart}
				disabled={product.stock === 0}
				class="bg-accent text-accent-foreground p-2 rounded-lg hover:opacity-90 transition-opacity disabled:opacity-50 disabled:cursor-not-allowed"
				title="Agregar al carrito"
			>
				<ShoppingCart size={20} />
			</button>
		</div>
	</div>
</div>

// components/product-card.tsx
"use client"

import type React from "react"

import Link from "next/link"
import Image from "next/image"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { ShoppingCart } from "lucide-react"
import type { Product } from "@/lib/types"
import { toast } from "@/hooks/use-toast"
import { mutate } from "swr"

interface ProductCardProps {
  product: Product
}

export function ProductCard({ product }: ProductCardProps) {
  const handleAddToCart = async (e: React.MouseEvent) => {
    e.preventDefault()

    try {
      const res = await fetch("/api/cart", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ productId: product.id, quantity: 1 }),
      })

      if (!res.ok) {
        const data = await res.json()
        throw new Error(data.error || "Failed to add to cart")
      }

      mutate("/api/cart")
      toast({
        title: "Added to cart",
        description: `${product.name} has been added to your cart`,
      })
    } catch (error) {
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to add to cart",
        variant: "destructive",
      })
    }
  }

  return (
    <Link href={`/products/${product.id}`}>
      <Card className="group overflow-hidden transition-shadow hover:shadow-lg">
        <div className="relative aspect-square overflow-hidden bg-muted">
          <Image
            src={product.image || "/placeholder.svg?height=400&width=400"}
            alt={product.name}
            fill
            className="object-cover transition-transform group-hover:scale-105"
          />
          {product.stock === 0 && (
            <div className="absolute inset-0 flex items-center justify-center bg-black/50">
              <span className="text-lg font-semibold text-white">Out of Stock</span>
            </div>
          )}
        </div>
        <CardContent className="p-4">
          <h3 className="line-clamp-1 font-semibold text-balance">{product.name}</h3>
          <p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{product.description}</p>
          <div className="mt-2 flex items-center justify-between">
            <span className="text-lg font-bold">${product.price.toFixed(2)}</span>
            {product.category && <span className="text-xs text-muted-foreground">{product.category}</span>}
          </div>
        </CardContent>
        <CardFooter className="p-4 pt-0">
          <Button className="w-full" onClick={handleAddToCart} disabled={product.stock === 0}>
            <ShoppingCart className="mr-2 h-4 w-4" />
            Add to Cart
          </Button>
        </CardFooter>
      </Card>
    </Link>
  )
}
